CREATE TABLE public.tableStatuses
(
    "STATUS_ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "STATUS" character varying(1000) COLLATE pg_catalog."default"

)